version: "3.9"
services:
  app:
    image: wishlist-magalu
    container_name: wishlist-magalu
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    ports: 
      - "5000:5000" 
      - "5678:5678"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: wishlist-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
