name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.16'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip==25.0.1
          pip install --no-cache-dir -r requirements.txt

      - name: Test with pylint
        run: |
          find . -type f -name "*.py" | xargs pylint

      - name: Test with pyunit
        run: |
          python -m unittest discover tests